import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'manual'}],
  typedocSidebar: [
    {
      type: 'category',
      label: 'XR Blocks API',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: typedocSidebar.items,
    },
  ],

  templatesSidebar: [{type: 'autogenerated', dirName: 'templates'}],

  samplesSidebar: [
    {
      type: 'category',
      label: 'Spatial UI',
      collapsed: false,
      items: ['samples/ModelViewer', 'samples/UI'],
    },
    {
      type: 'category',
      label: 'XR Realism',
      collapsed: false,
      items: [
        'samples/Occlusion',
        'samples/DepthMap',
        'samples/DepthMesh',
        'samples/Reticle',
        'samples/Lighting',
      ],
    },
    {
      type: 'category',
      label: 'XR Interaction',
      collapsed: false,
      items: [
        'samples/XR-Emoji',
        'samples/Custom-Gestures',
        'samples/RockPaperScissors',
      ],
    },
    {
      type: 'category',
      label: 'AI + XR',
      collapsed: false,
      items: [
        'samples/XR-Poet',
        'samples/Gemini-XRObject',
        'samples/Gemini-Icebreakers',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Demos',
      collapsed: false,
      items: [
        'samples/Ballpit',
        'samples/BalloonPop',
        'samples/Paint',
        'samples/Splash',
        'samples/Rain',
        'samples/ScreenWiper',
        'samples/Drone',
        'samples/Math-Tutor',
        'samples/AI-Simulator',
        'samples/Virtual-Screens',
        'samples/3DGS-Walkthrough',
      ],
    },
  ],
};

export default sidebars;
